apiVersion: v1
kind: Service
metadata:
  name: nexora-core
  namespace: nexora
spec:
  selector:
    app: nexora-core
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP
