CREATE INDEX IF NOT EXISTS idx_tenant_slug ON tenant(slug);
CREATE INDEX IF NOT EXISTS idx_party_tenant_type ON party(tenant_id, party_type);
CREATE INDEX IF NOT EXISTS idx_party_document_party ON party_document(party_id);
CREATE INDEX IF NOT EXISTS idx_auth_user_email ON auth_user(email);
CREATE INDEX IF NOT EXISTS idx_auth_user_tenant ON auth_user(tenant_id);
CREATE INDEX IF NOT EXISTS idx_auth_session_user ON auth_session(user_id);
CREATE INDEX IF NOT EXISTS idx_auth_session_access ON auth_session(access_token);
CREATE INDEX IF NOT EXISTS idx_service_request_tenant_status ON service_request(tenant_id, status);
CREATE INDEX IF NOT EXISTS idx_service_request_module ON service_request(module_code);
CREATE INDEX IF NOT EXISTS idx_notification_user_unread ON notification_event(user_id, read_at);
CREATE INDEX IF NOT EXISTS idx_invoice_account ON invoice(billing_account_id);
CREATE INDEX IF NOT EXISTS idx_metric_snapshot_lookup ON metric_snapshot(metric_code, tenant_id, region_code);
CREATE INDEX IF NOT EXISTS idx_entity_attribute_entity ON entity_attribute_value(entity_type, entity_id, attribute_code);
CREATE INDEX IF NOT EXISTS idx_entity_link_from ON entity_link(from_entity_type, from_entity_id);
CREATE INDEX IF NOT EXISTS idx_entity_link_to ON entity_link(to_entity_type, to_entity_id);
CREATE INDEX IF NOT EXISTS idx_integration_link_external ON integration_link(external_system_id, local_entity_type, local_entity_id);
CREATE INDEX IF NOT EXISTS idx_replication_health_src_tgt ON replication_health(source_region_code, target_region_code);
CREATE INDEX IF NOT EXISTS idx_outbox_status ON outbox_event(status, created_at);
CREATE INDEX IF NOT EXISTS idx_inbox_topic_received ON inbox_event(topic, received_at);
