apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -staging
resources:
  - ../../base
patches:
  - target:
      kind: Deployment
      name: nexora-core
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 4
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: sa-east
